# Generated by Django 4.2.13 on 2026-05-20 13:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_name', models.CharField(help_text="e.g., 'header_banner', 'sidebar_1'", max_length=100, unique=True)),
                ('ad_type', models.CharField(choices=[('adsense', 'AdSense'), ('manual', 'Manual'), ('custom', 'Custom HTML')], max_length=20)),
                ('adsense_slot_id', models.CharField(blank=True, max_length=100)),
                ('manual_image_url', models.TextField(blank=True)),
                ('manual_link_url', models.TextField(blank=True)),
                ('manual_alt_text', models.CharField(blank=True, max_length=200)),
                ('manual_html', models.TextField(blank=True, help_text='Custom ad HTML/JS')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Ad Placements',
                'ordering': ['display_order', 'slot_name'],
            },
        ),
        migrations.CreateModel(
            name='BasketItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('unit', models.CharField(help_text="e.g., '1 kg (bulk)', '1 litre'", max_length=100)),
                ('brand', models.CharField(blank=True, max_length=200)),
                ('specification', models.TextField(blank=True, help_text='Detailed description for like-for-like comparison')),
                ('weight', models.DecimalField(decimal_places=6, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('scrape_source_primary', models.URLField(blank=True, max_length=500)),
                ('scrape_source_backup', models.URLField(blank=True, max_length=500)),
                ('scrape_frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual')], default='daily', max_length=20)),
                ('requires_manual_entry', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Basket Items',
                'ordering': ['group', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('code', models.CharField(help_text='ISO 3166-1 alpha-3', max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('currency_code', models.CharField(max_length=3)),
                ('currency_symbol', models.CharField(blank=True, max_length=5)),
                ('base_period', models.DateField(help_text='e.g., 2022-01-01')),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ScrapeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=200)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed')], max_length=20)),
                ('items_scraped', models.IntegerField(default=0)),
                ('items_failed', models.IntegerField(default=0)),
                ('error_log', models.TextField(blank=True)),
                ('source_url', models.TextField(blank=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scrape_logs', to='core.country')),
            ],
            options={
                'verbose_name_plural': 'Scrape Logs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coicop_code', models.CharField(blank=True, help_text="e.g., '01', '01.1'", max_length=10)),
                ('name', models.CharField(max_length=200)),
                ('weight', models.DecimalField(decimal_places=4, max_digits=8, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_core', models.BooleanField(default=True, help_text='Included in core CPI?')),
                ('is_active', models.BooleanField(default=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_groups', to='core.country')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.productgroup')),
            ],
            options={
                'verbose_name_plural': 'Product Groups',
                'ordering': ['country', 'coicop_code'],
                'unique_together': {('country', 'coicop_code')},
            },
        ),
        migrations.CreateModel(
            name='PriceAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation_date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('source_url', models.TextField()),
                ('source_name', models.CharField(max_length=200)),
                ('scrape_method', models.CharField(choices=[('automated', 'Automated'), ('manual', 'Manual'), ('api', 'API')], max_length=50)),
                ('product_page_title', models.TextField(blank=True)),
                ('product_page_snapshot', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_audit_logs', to='core.country')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='core.basketitem')),
            ],
            options={
                'verbose_name_plural': 'Price Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('summary', models.TextField(blank=True)),
                ('source_name', models.CharField(max_length=200)),
                ('source_url', models.TextField(unique=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(blank=True, choices=[('economy', 'Economy'), ('policy', 'Policy'), ('markets', 'Markets'), ('international', 'International')], max_length=50)),
                ('is_featured', models.BooleanField(default=False)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news_articles', to='core.country')),
            ],
            options={
                'verbose_name_plural': 'News Articles',
                'ordering': ['-published_at'],
            },
        ),
        migrations.AddField(
            model_name='basketitem',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basket_items', to='core.country'),
        ),
        migrations.AddField(
            model_name='basketitem',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.productgroup'),
        ),
        migrations.CreateModel(
            name='PriceObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation_date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency_code', models.CharField(max_length=3)),
                ('source_url', models.TextField(blank=True)),
                ('source_name', models.CharField(blank=True, max_length=200)),
                ('scrape_method', models.CharField(choices=[('automated', 'Automated'), ('manual', 'Manual'), ('api', 'API')], default='automated', max_length=50)),
                ('raw_data', models.JSONField(blank=True, help_text='Store raw scraped data for audit', null=True)),
                ('is_validated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_observations', to='core.country')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='core.basketitem')),
            ],
            options={
                'verbose_name_plural': 'Price Observations',
                'ordering': ['-observation_date', 'item'],
                'indexes': [models.Index(fields=['country', 'observation_date'], name='core_priceo_country_37eff6_idx'), models.Index(fields=['item', 'observation_date'], name='core_priceo_item_id_32c5cb_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_date', models.DateField()),
                ('base_currency', models.CharField(default='USD', max_length=3)),
                ('local_currency', models.CharField(max_length=3)),
                ('rate', models.DecimalField(decimal_places=4, help_text='Local per 1 USD', max_digits=12)),
                ('source', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_rates', to='core.country')),
            ],
            options={
                'verbose_name_plural': 'Exchange Rates',
                'ordering': ['-rate_date'],
                'unique_together': {('country', 'rate_date', 'base_currency')},
            },
        ),
        migrations.CreateModel(
            name='CPIIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_date', models.DateField(help_text='First of month')),
                ('index_type', models.CharField(choices=[('headline', 'Headline CPI'), ('core', 'Core CPI'), ('food', 'Food CPI'), ('non_food', 'Non-Food CPI')], max_length=30)),
                ('index_value', models.DecimalField(decimal_places=4, max_digits=10)),
                ('yoy_inflation', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('mom_inflation', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('ma12_inflation', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('base_period', models.DateField()),
                ('methodology_note', models.TextField(blank=True)),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cpi_indices', to='core.country')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cpi_indices', to='core.productgroup')),
            ],
            options={
                'verbose_name_plural': 'CPI Indices',
                'ordering': ['-period_date', 'index_type'],
                'unique_together': {('country', 'period_date', 'index_type', 'group')},
            },
        ),
    ]
