# Generated by Django 4.2.13 on 2026-05-27 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_date', models.DateField()),
                ('rate_type', models.CharField(choices=[('exchange_rate', 'Exchange Rate'), ('awplr', 'AWPLR — Average Weighted Prime Lending Rate'), ('awfdr', 'AWFDR — Average Weighted Fixed Deposit Rate'), ('tbill_91', 'Treasury Bill — 91 Day'), ('tbill_182', 'Treasury Bill — 182 Day'), ('tbill_364', 'Treasury Bill — 364 Day'), ('sdfr', 'Standing Deposit Facility Rate (SDFR)'), ('slfr', 'Standing Lending Facility Rate (SLFR)'), ('opr', 'Overnight Policy Rate (OPR)')], max_length=30)),
                ('currency', models.CharField(blank=True, help_text='For exchange rates', max_length=3)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('source', models.CharField(blank=True, default='CBSL', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_rates', to='core.country')),
            ],
            options={
                'verbose_name_plural': 'Market Rates',
                'ordering': ['-rate_date', 'rate_type'],
                'unique_together': {('country', 'rate_date', 'rate_type', 'currency')},
            },
        ),
        migrations.CreateModel(
            name='BankExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=200)),
                ('rate_date', models.DateField()),
                ('currency', models.CharField(max_length=3)),
                ('buying_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('selling_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('tt_buying_rate', models.DecimalField(blank=True, decimal_places=4, help_text='Telegraphic Transfer buying', max_digits=12, null=True)),
                ('tt_selling_rate', models.DecimalField(blank=True, decimal_places=4, help_text='Telegraphic Transfer selling', max_digits=12, null=True)),
                ('source_url', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_exchange_rates', to='core.country')),
            ],
            options={
                'verbose_name_plural': 'Bank Exchange Rates',
                'ordering': ['-rate_date', 'bank_name', 'currency'],
                'unique_together': {('country', 'bank_name', 'rate_date', 'currency')},
            },
        ),
    ]
