# Generated by Django 4.2.13 on 2026-06-02 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_youtube_video_model'),
        ('core', '0002_marketrate_bankexchangerate'),
    ]

    operations = [
    ]
