# Generated by Django 4.2.13 on 2026-07-06 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_merge_20260602_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpiindex',
            name='index_type',
            field=models.CharField(choices=[('headline', 'Headline CPI'), ('core', 'Core CPI'), ('food', 'Food CPI'), ('non_food', 'Non-Food CPI'), ('official_ccpi', 'Official CCPI (CBSL/DCS, 2021=100)'), ('official_core_ccpi', 'Official Core CCPI (CBSL/DCS, 2021=100)')], max_length=30),
        ),
        migrations.CreateModel(
            name='ScrapeSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(help_text='e.g., Keells, Spar, CEYPETCO', max_length=200)),
                ('url', models.URLField(max_length=1000)),
                ('selector_type', models.CharField(choices=[('css', 'CSS Selector'), ('xpath', 'XPath'), ('regex', 'Regex on full page')], default='css', max_length=20)),
                ('selector', models.TextField(help_text='CSS selector, XPath, or regex pattern')),
                ('price_regex', models.CharField(blank=True, help_text="Optional regex to extract numeric price from selected text (e.g., '([0-9,]+\\.\\d{2})')", max_length=255)),
                ('price_multiplier', models.DecimalField(decimal_places=4, default=1, help_text="Multiply scraped price by this factor (e.g., 1000 for 'per kg' if site shows per gram)", max_digits=10)),
                ('currency_code', models.CharField(default='LKR', max_length=3)),
                ('requires_js', models.BooleanField(default=False, help_text='Use Playwright for JavaScript-rendered pages')),
                ('is_active', models.BooleanField(default=True)),
                ('scrape_frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual')], default='daily', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Any notes about this source')),
                ('last_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('last_price_date', models.DateField(blank=True, null=True)),
                ('last_status', models.CharField(blank=True, max_length=20)),
                ('last_error', models.TextField(blank=True)),
                ('last_scraped_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrape_sources', to='core.country')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrape_sources', to='core.basketitem')),
            ],
            options={
                'verbose_name_plural': 'Scrape Sources',
                'ordering': ['item__name', 'source_name'],
            },
        ),
    ]
